---
exclude: /(bin|build|gradle)$
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: double-quote-string-fixer
          - id: trailing-whitespace

    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.11.0
      hooks:
          - id: pretty-format-java
            args: [--autofix]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt
